language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2
install:
- nuget restore
- nuget install NUnit.Console -Version 3.9.0 -OutputDirectory testrunner
script:
- dotnet restore
- dotnet build
- dotnet test
global:
- DOTNET_SKIP_FIRST_TIME_EXPERIENCE=true
- DOTNET_CLI_TELEMETRY_OPTOUT=1
